USE [master]
GO

/****** Object:  Database [tipo_cambio]    Script Date: 16/10/2018 20:40:06 ******/
CREATE DATABASE [tipo_cambio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tipo_cambio', FILENAME = N'D:\RDSDBDATA\DATA\tipo_cambio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'tipo_cambio_log', FILENAME = N'D:\RDSDBDATA\DATA\tipo_cambio_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [tipo_cambio] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tipo_cambio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [tipo_cambio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [tipo_cambio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [tipo_cambio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [tipo_cambio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [tipo_cambio] SET ARITHABORT OFF 
GO

ALTER DATABASE [tipo_cambio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [tipo_cambio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [tipo_cambio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [tipo_cambio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [tipo_cambio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [tipo_cambio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [tipo_cambio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [tipo_cambio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [tipo_cambio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [tipo_cambio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [tipo_cambio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [tipo_cambio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [tipo_cambio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [tipo_cambio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [tipo_cambio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [tipo_cambio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [tipo_cambio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [tipo_cambio] SET RECOVERY FULL 
GO

ALTER DATABASE [tipo_cambio] SET  MULTI_USER 
GO

ALTER DATABASE [tipo_cambio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [tipo_cambio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [tipo_cambio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [tipo_cambio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [tipo_cambio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [tipo_cambio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [tipo_cambio] SET  READ_WRITE 
GO

